development:
  adapter: postgresql
  encoding: unicode
  database: hq_dev
  pool: 2
  username: hq_username
  password: hq_password

production:
  adapter: postgresql
  encoding: unicode
  database: hq_prod
  pool: 2
  username: hq_username
  password: hq_password